I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/screens.rpy", line 380, in prepare_screen
    screen menu_help():
  File "game/screens.rpy", line 380, in prepare
    screen menu_help():
  File "game/screens.rpy", line 382, in prepare
    textbutton _("Return"):
  File "game/screens.rpy", line 382, in prepare
    textbutton _("Return"):
TypeError: __init__() takes at least 2 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\main.py", line 94, in run
    renpy.display.screen.prepare_screens()
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\screen.py", line 931, in prepare_screens
    s.ast.prepare_screen()
  File "game/screens.rpy", line 380, in prepare_screen
    screen menu_help():
  File "game/screens.rpy", line 380, in prepare
    screen menu_help():
  File "game/screens.rpy", line 382, in prepare
    textbutton _("Return"):
  File "game/screens.rpy", line 382, in prepare
    textbutton _("Return"):
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<screen language>", line 383, in <module>
TypeError: __init__() takes at least 2 arguments (1 given)

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Stalker v0.1.0.2
Mon Mar 23 03:14:34 2020
